### ISSUE TITLE
[Task] Fedora 36 upgrade breaks hot-reloading dev server

### ISSUE THREAD

**Issue by hareetd** [cryostatio/cryostat-web#451]
Attempts to run the hot-reloading development server post-Fedora 36 upgrade are met with the following error: 

```
[hdhillon@localhost cryostat-web]$ npm run start:dev

> cryostat-web@0.0.1 start:dev
> webpack serve --hot --color --progress --config webpack.dev.js

10% building 0/1 entries 0/0 dependencies 0/0 modulesℹ ｢wds｣: Project is running at http://localhost:9000/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from ./dist
ℹ ｢wds｣: 404s will fallback to /index.html
node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at BulkUpdateDecorator.hashFactory (/home/hdhillon/Workspace/cryostat-web/node_modules/webpack/lib/util/createHash.js:155:18)
    at BulkUpdateDecorator.update (/home/hdhillon/Workspace/cryostat-web/node_modules/webpack/lib/util/createHash.js:46:50)
    at OriginalSource.updateHash (/home/hdhillon/Workspace/cryostat-web/node_modules/webpack-sources/lib/OriginalSource.js:131:8)
    at NormalModule._initBuildHash (/home/hdhillon/Workspace/cryostat-web/node_modules/webpack/lib/NormalModule.js:888:17)
    at handleParseResult (/home/hdhillon/Workspace/cryostat-web/node_modules/webpack/lib/NormalModule.js:954:10)
    at /home/hdhillon/Workspace/cryostat-web/node_modules/webpack/lib/NormalModule.js:1048:4
    at processResult (/home/hdhillon/Workspace/cryostat-web/node_modules/webpack/lib/NormalModule.js:763:11)
    at /home/hdhillon/Workspace/cryostat-web/node_modules/webpack/lib/NormalModule.js:827:5 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
[hdhillon@localhost cryostat-web]$ node:internal/process/promises:265
            triggerUncaughtException(err, true /* fromPromise */);
            ^

RpcIpcMessagePortClosedError: Cannot send the message - the message port has been closed for the process 11313.
    at /home/hdhillon/Workspace/cryostat-web/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/rpc-ipc/RpcIpcMessagePort.js:47:47
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: undefined,
  signal: undefined
}
node:internal/process/promises:265
            triggerUncaughtException(err, true /* fromPromise */);
            ^

RpcIpcMessagePortClosedError: Cannot send the message - the message port has been closed for the process 11312.
    at /home/hdhillon/Workspace/cryostat-web/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/rpc-ipc/RpcIpcMessagePort.js:47:47
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: undefined,
  signal: undefined
}
```
It seems the OS upgrade changes the OpenSSL version to one which doesn't support MD4, the default hashing algorithm used by Webpack.

**Comment by hareetd** [comment]
This bug actually affects all the `webpack` scripts in `package.json` (i.e. `build`, `build::notests`, `start:dev`, and `build:bundle-profile`.
