### ISSUE TITLE
Deleting automated rule deletes active recording twice for aliased targets

### ISSUE THREAD

**Issue by jan-law** [cryostatio/cryostat-web#455]
Related to #325?

If there are multiple connect URLs pointing to the same target, and an automated rule's match expression matches both URLs, deleting the automated rule will attempt to delete the active recording associated with that automated rule twice. The second attempt results in a `RecordingNotFoundException` logged in the backend.

1) Add a custom target with connect URL `cryostat:9093`
2) Start an automated rule with match expression `true` to match all target connect URLs
3) Delete the automated rule. All active automated rule recordings will get deleted, and this exception is thrown:

```
INFO: Connection for service:jmx:rmi:///jndi/rmi://cryostat:9093/jmxrmi closed
Jun 09, 2022 7:26:42 PM io.cryostat.core.log.Logger error
SEVERE: Exception thrown
java.util.concurrent.ExecutionException: io.cryostat.recordings.RecordingNotFoundException: Recording auto_test not found in target active recordings
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
	at io.cryostat.rules.PeriodicArchiver.performArchival(PeriodicArchiver.java:154)
	at io.cryostat.rules.PeriodicArchiver.run(PeriodicArchiver.java:132)
	at io.cryostat.rules.RuleProcessor.lambda$activate$8(RuleProcessor.java:219)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:889)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:860)
	at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:50)
	at io.vertx.core.impl.DuplicatedContext.emit(DuplicatedContext.java:168)
	at io.vertx.core.impl.AbstractContext.emit(AbstractContext.java:53)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.run(VertxImpl.java:883)
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:176)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by andrewazores** [comment]
This is a backend bug:

https://github.com/cryostatio/cryostat/blob/fd7a2d85c5885c317c9080cc937ee6da59641da0/src/main/java/io/cryostat/net/web/http/api/v2/RuleDeleteHandler.java#L150

It stems from our same usual problem with these so-called "aliased JMX URLs". Rule deletion is implemented by iterating over all discovered targets and trying to delete the recording corresponding to the rule. If two of the discovered targets are really the same JVM then the second (third, fourth, etc.) deletion will fail because the recording has already been deleted.

**Comment by maxcao13** [comment]
I see a different exception now. The handler now tries to stop an already stopped recording.
```java
Jan 30, 2023 8:35:30 PM io.cryostat.core.log.Logger error
SEVERE: Exception thrown
org.openjdk.jmc.rjmx.services.jfr.FlightRecorderException: Could not stop the recording!
	at org.openjdk.jmc.rjmx.services.jfr.internal.FlightRecorderServiceV2.stop(FlightRecorderServiceV2.java:150)
	at org.openjdk.jmc.rjmx.services.jfr.internal.FlightRecorderServiceV2.stop(FlightRecorderServiceV2.java:143)
	at io.cryostat.recordings.RecordingTargetHelper.lambda$stopRecording$6(RecordingTargetHelper.java:307)
	at io.cryostat.net.TargetConnectionManager.executeConnectedTask(TargetConnectionManager.java:168)
	at io.cryostat.recordings.RecordingTargetHelper.stopRecording(RecordingTargetHelper.java:295)
	at io.cryostat.recordings.RecordingTargetHelper.stopRecording(RecordingTargetHelper.java:288)
	at io.cryostat.net.web.http.api.v2.RuleDeleteHandler.lambda$cleanup$1(RuleDeleteHandler.java:175)
	at io.vertx.core.impl.ContextBase.lambda$null$0(ContextBase.java:137)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264)
	at io.vertx.core.impl.ContextBase.lambda$executeBlocking$1(ContextBase.java:135)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: javax.management.RuntimeMBeanException: java.lang.IllegalStateException: Can't stop an already stopped recording.
```
