### ISSUE TITLE
[Task] Fix tests' warnings on missing wrapping act

### ISSUE THREAD

**Issue by tthvo** [cryostatio/cryostat-web#792]
Starting to see these similar warnings in many places in tests:

```bash
    console.error
      Warning: An update to Popper inside a test was not wrapped in act(...).
      
      When testing, code that causes React state updates should be wrapped into act(...):
      
      act(() => {
        /* fire events that update state */
      });
      /* assert on the output */
      
      This ensures that you're testing the behavior the user would see in the browser. Learn more at https://reactjs.org/link/wrap-tests-with-act
          at Popper (/home/thvo/workspace/cryostat-web/node_modules/@patternfly/react-core/dist/js/helpers/Popper/Popper.js:28:26)
          at GenerateId (/home/thvo/workspace/cryostat-web/node_modules/@patternfly/react-core/dist/js/helpers/GenerateId/GenerateId.js:20:5)
          at Select (/home/thvo/workspace/cryostat-web/node_modules/@patternfly/react-core/dist/js/components/Select/Select.js:33:5)
          at Component (/home/thvo/workspace/cryostat-web/src/app/Settings/CredentialsStorage.tsx:75:43)
          at Wrapper (/home/thvo/workspace/cryostat-web/src/test/Common.tsx:59:30)

```

Seem to affect tests on component that has a Popper in its sub-tree. Maybe some deps upgrade update Popper somewhere?

**Comment by tthvo** [comment]
Might be a false positive caused by some test package internals. Not seeing anymore this issue anymore as of https://github.com/cryostatio/cryostat-web/tree/3912e4c8bf1afa3d08f2b74238ed124f9e4e3031
